# Site settings
title: Ben Carothers 
header-img: img/home-bg.jpg
email: benjamin.carothers13@ncf.edu
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/ben"
url: "http://bencarothers.me"
twitter_username: bntcrs 
github_username: bencarothers 
facebook_username: benjamin.carothers.1 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
