# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Ben Carothers
tagline:             The Jekyll Butler
url:                 http://bencarothers.me
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Ben Carothers 
  url:               https://twitter.com/carothersb
  email:             benjamin.carothers13@ncf.edu

# Custom vars
version:             2.0.0
github:              https://github.com/bencarothers
