# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ben Carothers 
tagline:          'The personal website of Ben Carothers'
description:      'The personal website of Ben Carothers'
url:              bencarothers.me

author:
  name:           'Ben Carothers'
  url:            https://twitter.com/CarothersB

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/bencarothers/bencarothers.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive'}
